stomory/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings as settings
from django.contrib import admin

from allauth.account import views as allauth_views
from allauth.socialaccount import views as socialaccount_views
from allauth.socialaccount.providers.facebook.views import oauth2_login as facebook_login
from allauth.socialaccount.providers.facebook.views import oauth2_callback as facebook_login_callback
 
#from dajaxice.core import dajaxice_autodiscover, dajaxice_config

from dajaxice.core import dajaxice_autodiscover

from stomory import settings as stomory_settings
from stomory.app.account.forms import CustomSignupForm, CustomResetPasswordForm, CustomSocialSignupForm
from stomory.app.app_settings import SIGNUP_TEMPLATE, SIGNUP_SUCCESS_URL, SOCIAL_SIGNUP_TEMPLATE
from stomory.app.app_settings import LOGIN_TEMPLATE, PASSWORD_RESET_TEMPLATE
from stomory.app.app_settings import PASSWORD_RESET_TEMPLATE_DONE
from stomory.app.account import views as stomory_account_views
from stomory.app.member.views import settings as profile_settings_view
from stomory.app.main import views as story_main_views
from stomory.settings import LOGOUT_REDIRECT_URL

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Admin URL
    url(r'^admin/', include(admin.site.urls)),

    # Allauth app URL
    url(r"^signup/$",   stomory_account_views.signup, 
                        {
                            'template_name': SIGNUP_TEMPLATE,
                            'success_url': SIGNUP_SUCCESS_URL,
                            'form_class': CustomSignupForm 
                        }
                        , name="account_signup"),
    url(r"^login/$",    stomory_account_views.login,   
                        {
                            'template_name': LOGIN_TEMPLATE
                        }
                        , name="account_login"),
    url(r"^accounts/facebook/login/$", facebook_login, {}, name='facebook_login'),
    url(r"^accounts/facebook/login/callback/$", facebook_login_callback, {}, name='facebook_callback'),
    url(r"^accounts/social/signup/$",   socialaccount_views.signup,
                                        {
                                            "template_name": SOCIAL_SIGNUP_TEMPLATE,
                                            'form_class': CustomSocialSignupForm 
                                        }
                                        , name='socialaccount_signup'),

    url(r"^password/change/$", allauth_views.password_change, {'template_name': 'app/account/password_change.html'}, name="account_change_password"),
    url(r"^password/set/$", allauth_views.password_set, name="account_set_password"),
    url(r"^logout/$", allauth_views.logout, {
                                        'next_page': LOGOUT_REDIRECT_URL,
                                    }
                                    , name="account_logout"),
    url(r"^password/reset/$",   allauth_views.password_reset, 
                                {
                                    'template_name': PASSWORD_RESET_TEMPLATE,
                                    'form_class': CustomResetPasswordForm
                                }
                                , name="account_reset_password"),
    url(r"^password/reset/done/$",  allauth_views.password_reset_done, 
                                    {
                                        'template_name': PASSWORD_RESET_TEMPLATE_DONE
                                    }
                                    , name="account_reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", allauth_views.password_reset_from_key, name="account_reset_password_from_key"),

    # Custom Account URL
    url(r'^confirmation/resend/',stomory_account_views.resend_confirmation, name="account_resend_confirm_email"),
    url(r'^confirmation/(?P<confirmation_key>\w+)/',stomory_account_views.confirmation, name="account_confirm_email"),

    # stomory URL
    url(r'^$', include('stomory.app.main.urls')),
    url(r'^error/$', story_main_views.error_page),  
    url(r"^search/$",story_main_views.search_story),
    url(r"^filter/$",story_main_views.filter_story),
    url(r"^sort/$",story_main_views.sort_story),

    url(r'^story/', include('stomory.app.story.urls')),
    url(r'^settings/$', profile_settings_view),

    # Dajaxice URL
    url(r'^%s/' % stomory_settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

    # Media URL
    url(r'^asset/media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    
    # Final URL - Member page
    url(r'^(?P<username>\w+)/',include('stomory.app.member.urls')),
)

stomory/app/account/models.py
import datetime
from random import random

from django.core.mail import EmailMultiAlternatives
from django.utils.html import strip_tags
from django.conf import settings
from django.db import models, IntegrityError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse, NoReverseMatch
from django.template.loader import render_to_string
from django.utils.hashcompat import sha_constructor
from django.utils.translation import gettext_lazy as _

from django.contrib.sites.models import Site
from django.contrib.auth.models import User

from allauth.account.signals import email_confirmed, email_confirmation_sent

from stomory.settings import WEBSITE_HOMEPAGE

# this code based in-part on django-registration
class StomoryEmailAddressManager(models.Manager):
    
    def add_email(self, user, email):
        try:
            email_address = self.create(user=user, email=email)
            StomoryEmailConfirmation.objects.send_confirmation(email_address)
            return email_address
        except IntegrityError:
            return None
    
    def get_primary(self, user):
        try:
            return self.get(user=user, primary=True)
        except stomoryEmailAddress.DoesNotExist:
            return None
    
    def get_users_for(self, email):
        """
        returns a list of users with the given email.
        """
        # this is a list rather than a generator because we probably want to
        # do a len() on it right away
        return [address.user for address in stomoryEmailAddress.objects.filter(
            verified=True, email=email)]


class StomoryEmailAddress(models.Model):
    
    user = models.ForeignKey(User)
    email = models.EmailField()
    verified = models.BooleanField(default=False)
    primary = models.BooleanField(default=False)
    
    objects = StomoryEmailAddressManager()
    
    def set_as_primary(self, conditional=False):
        old_primary = stomoryEmailAddress.objects.get_primary(self.user)
        if old_primary:
            if conditional:
                return False
            old_primary.primary = False
            old_primary.save()
        self.primary = True
        self.save()
        self.user.email = self.email
        self.user.save()
        return True
    
    def __unicode__(self):
        return u"%s (%s)" % (self.email, self.user)
    
    class Meta:
        verbose_name = _("email address")
        verbose_name_plural = _("email addresses")
        unique_together = (
            ("user", "email"),
        )

class StomoryEmailConfirmation(models.Model):
    email_address = models.EmailField()
    sent = models.DateTimeField()
    confirmation_key = models.CharField(max_length=40,blank=True)
    
    def confirm_email(self, confirmation_key):
        try:
            email_confirmation = self.get(confirmation_key=confirmation_key)
        except self.model.DoesNotExist:
            return None
        if not email_confirmation.key_expired():
            #email_confirmation.verified = True
            email_confirmation.save()
            return email_address

    def send_confirmation(self):
        confirmation_key = self.confirmation_key
        activate_url = WEBSITE_HOMEPAGE + 'confirmation/' + confirmation_key
        context = {
            "activate_url": activate_url,
        }
        subject = "Welcome to stomory"
        html_content = render_to_string('text/email/emailconfirmation/email_confirmation_message.html',context)
        text_content = strip_tags(html_content)
        mail = EmailMultiAlternatives(subject, text_content, settings.DEFAULT_FROM_EMAIL, [self.email_address])
        mail.attach_alternative(html_content, "text/html")
        mail.send()
        #send_mail(subject, message, settings.DEFAULT_FROM_EMAIL, [self.email_address])
        email_confirmation_sent.send(
            sender=self,
            confirmation=self,
        )

    def delete_expired_confirmations(self):
        for confirmation in self.all():
            if confirmation.key_expired():
                confirmation.delete()

    def key_expired(self):
        expiration_date = self.sent + datetime.timedelta(
            days=settings.EMAIL_CONFIRMATION_DAYS)
        return expiration_date <= datetime.datetime.now()
    key_expired.boolean = True
    
    def save(self, *args, **kwargs):
        salt = sha_constructor(str(random())).hexdigest()[:5]
        self.confirmation_key = sha_constructor(salt + self.email_address).hexdigest()
        super(StomoryEmailConfirmation, self).save(*args, **kwargs)

    def __unicode__(self):
        return u"confirmation for %s" % self.email_address
    
    class Meta:
        verbose_name = _("email confirmation")
        verbose_name_plural = _("email confirmations")

stomory/app/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

import datetime
import uuid 

########################################
#                                      #
#           CONSTANT DATA              #
#                                      #
########################################
GENDER = (
      ("1","Male"),
      ('0',"Female")
    )

PRIVACY_STATUS = (
  ("1","Public"),
  ("0","Private"),
)

YES_NO = (
  ("1","Yes"),
  ("0","No"),
)

# User profile Model
class UserProfile(models.Model):
    # This field is required.
    user = models.ForeignKey(User, unique=True)

    gender = models.CharField(max_length=1,choices=GENDER)
    basic_info = models.TextField(blank=True)
    #avatar = models.ImageField("Profile Picture", upload_to="uploads/img/member/")
    #avatar = models.TextField(blank=True,null=True)
    is_fb_account = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.user)
    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

class Comment(models.Model):
  #comment_story = models.ForeignKey(Story,related_name='comment_story')
  comment_by = models.ForeignKey(User,related_name='comment_by')
  content = models.TextField()
  #content_html = models.TextField(editable=False, blank=True)
  created_date = models.DateTimeField(default=datetime.datetime.now())
  #created_elapse_time = models.CharField(max_length=50)
  #edit_date =  models.DateTimeField(blank=True,null=True)
  #edit_elapse_time = models.CharField(max_length=50,blank=True,null=True)
  class Meta:
    ordering = ['created_date']
      
  # def save(self, *args, **kwargs):
  #   now = datetime.datetime.now()
  #   created_elapse = now - self.created_date
  #   self.created_elapse_time = get_elapse_time(int(created_elapse.total_seconds())) 
  #   if self.edit_date != None:
  #       edit_elapse = now - self.edit_date
  #       self.edit_elapse_time = get_elapse_time(edit_elapse.total_seconds())
  #   self.content_html = markdown(self.content.replace("\n","<br>").replace(" ","&nbsp;"))
  #   super(Comment, self).save(*args, **kwargs)


class StoryCategory(models.Model):
  category_logo = models.ImageField("Category Logo", upload_to="default/img/category_story/")
  #category_logo = models.TextField(blank=True,null=True)	
  name = models.CharField(max_length=30)
  description = models.CharField(max_length=100)
  def __unicode__(self):
    return unicode(self.name)
    
class Story(models.Model):
  title = models.CharField(max_length=300)
  theme_picture = models.ImageField("Story Picture", upload_to="uploads/img/story/", blank=True, null=True) 
  #theme_picture = models.TextField(blank=True,null=True) 
  content = models.TextField()
  created_date = models.DateTimeField(default=datetime.datetime.now())
  privacy_status = models.CharField(max_length=1,choices=PRIVACY_STATUS,default='1')
  #social_publish = models.CharField(max_length=1,choices=YES_NO,default='1')
  category = models.ForeignKey(StoryCategory, related_name="category")
  created_by = models.ForeignKey(User, related_name="create_by")
  follow_by = models.ManyToManyField(User, related_name="follow_by",blank=True,null=True)
  comment = models.ManyToManyField(Comment,related_name='comment',blank=True,null=True)
  num_like = models.IntegerField(default=0)
  def __unicode__(self):
    return unicode(self.title)

class Report(models.Model):
  report_story = models.ForeignKey(Story,related_name='report_story')
  report_by = models.ForeignKey(User,related_name='report_by')
  date = models.DateTimeField(default=datetime.datetime.now())
  reason = models.TextField()
  class Meta:
    ordering = ['date']

class Like(models.Model):
  story = models.ForeignKey(Story,related_name='story')
  user = models.ForeignKey(User,related_name='user')

stomory/app/account/views.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from django.template import RequestContext
from django.shortcuts import render_to_response

from stomory.helper.common import get_user_login_object
from stomory.helper.account import resend_email_confirmation
from stomory.app.account.models import StomoryEmailConfirmation, StomoryEmailAddress

from allauth.account.views import login as allauth_login
from allauth.account.views import signup as allauth_signup

# Create your views here.
def resend_confirmation(request):
    user_login = get_user_login_object(request)
    resend_email_confirmation(user_login)
    print "here"
    return HttpResponseRedirect("/?action=resend_confirm_email&result=success")

def confirmation(request,confirmation_key):
    e = StomoryEmailConfirmation.objects.filter(confirmation_key=confirmation_key)
    if len(e) == 0:
      return HttpResponseRedirect("/?action=confirm_email&result=error")
    else:     
      try:
        email = e[0].email_address
        emailAddress = StomoryEmailAddress.objects.get(email=email)
        emailAddress.verified = True
        emailAddress.save()    	
        return HttpResponseRedirect("/?action=confirm_email&result=success")
      except:
        return HttpResponseRedirect("/?action=confirm_email&result=error")

def signup(request,**kwargs):
    user_login = get_user_login_object(request)
    if user_login:
        return HttpResponseRedirect("/")
    else:
        return allauth_signup(request,**kwargs)

def login(request,**kwargs):
    user_login = get_user_login_object(request)
    if user_login:
        return HttpResponseRedirect("/")
    else:
        return allauth_login(request,**kwargs)

stomory/asset/templates/app/account/page/login.html
{% extends "app/account/account_base.html" %}

{% block main_section %}
    		<div class="signin-section">
				<div class="signin-header row-fluid">
					<div class="header-text pull-left">
						Sign In
					</div>
					<div class="signin-fb pull-right">
						<a href='/accounts/facebook/login'>
							<input src="{{STATIC_URL}}img/app/account/signin-fb-btn.png" style="margin:10px 5px 0px 5px" type="image" alt="Signin with Facebook">
						</a>
					</div>
				</div>
				<div class="signin-content row-fluid">
					 <form class="login" id="login_form" method="post" action="/login/">{% csrf_token %}
						<div class='non-field-error row-fluid'>
                            {{ form.non_field_errors }}
                        </div>
						<div class="email-password-section row-fluid">
							<div class="email-field pull-left">
								<label for="id_login" class="title">
									Email
								</label>
								{{form.login.errors}}
								<div class="input-field">
									{{form.login}}
								</div>
							</div>
							<div class="password-field pull-left">
								<label for="id_password" class="title">
									Password
								</label>
								{{form.password.errors}}
								<div class="input-field">
									{{form.password}}
								</div>
							</div>
						</div>
						<div class="complete-section">
							 {% if redirect_field_value %}
        						<input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        					{% endif %}
							<div class="remember-me pull-left">
								<input type="checkbox" name="_spring_security_remember_me" checked="checked">
								<span>Remember Me</span>
							</div>
							<div class="signin-btn pull-right">
								<input id="signin-btn" type="image" src="{{STATIC_URL}}img/app/account/signin-btn.png" alt="Sign in">
							</div>
						</div>
					</form>
				</div>
				<div class="signin-footer row-fluid">
					<div class="forgot-section pull-left">
						<div class="forgot-item pull-left">
							<a href="/password/reset">Forgot Password?</a>
						</div>
					</div>
					<div class="content pull-right">
						New to Stomory? <a href="/signup">Register</a>
					</div>
				</div>
			</div>


{% endblock %}

stomory/asset/templates/app/account/page/password_reset.html
{% extends "app/account/account_base.html" %}

{% block main_section %}
			<div class="reset-password-section">
				<div class="reset-password-header row-fluid">
					<div class="header-text pull-left">
						Reset Password
					</div>
				</div>
				<div class="reset-password-content row-fluid">
					<form method="POST" action="" class="password_reset"> {% csrf_token %}
						<div class="email-section row-fluid">
							<label for="id_email" class="title" style="">
								Email
							</label>
							{{ password_reset_form.email.errors }}
							<div class="input-field">
								{{ password_reset_form.email }}
							</div>
							<!-- <input type="text" id="username_input" name="username_input" placeholder="Username" maxlength="50" class="valid"> -->
						</div>
						<div class="complete-section">
							<div class="submit-btn">
								<input type="image" src="//db0dp9rjtl3zs.cloudfront.net/zaahah.com/v3/img/app/forgot_page/submit-btn.png">
							</div>
						</div>
					</form>
				</div>
			</div>
{% endblock %}

stomory/asset/templates/app/account/page/password_reset_done.html
{% extends "app/account/account_base.html" %}

{% block main_section %}
			<div class="reset-password-section">
				<div class="reset-password-header row-fluid">
					<div class="header-text pull-left">
						Reset Password
					</div>
				</div>
				<div class="reset-password-content row-fluid">
					<div class='complete-message'>
						We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.
					</div>
				</div>
			</div>

{% endblock %}

stomory/asset/templates/app/account/page/signup.html
{% extends "app/account/account_base.html" %}

{% block main_section %}

            <div class="register-section">
                <div class="register-header row-fluid">
                    <div class="header-text pull-left">
                        Signup
                    </div>
                    <div class="join-fb pull-right">
                       <a href='/accounts/facebook/login/'>
                            <input src="{{STATIC_URL}}img/app/account/signin-fb-btn.png" style="margin:10px 5px 0px 5px" type="image" alt="Signin with Facebook">
                        </a>
                    </div>
                </div>
                <div class="register-content row-fluid">
                     <form class="signup" id="signup_form" method="post" action="{% url account_signup %}">{% csrf_token %}
                        <div class='non-field-error row-fluid'>
                            {{ form.non_field_errors }}
                        </div>
                        <div class="name-section data-row row-fluid">
                            <div class="firstname-field pull-left">
                                <label for="id_first_name" class="title">
                                    First Name
                                </label>
                                {{ form.first_name.errors }}
                                <div class="input-field">
                                    {{form.first_name}}
                                </div>
                            </div>
                            <div class="lastname-field pull-right">
                                <label for="id_last_name" class="title">
                                    Last Name
                                </label>
                                {{form.last_name.errors}}
                                <div class="input-field">
                                    {{form.last_name}}                                
                                </div>
                            </div>
                        </div>

                        <div class="password-section data-row row-fluid">
                            <div class="password-field pull-left">
                                <label for="id_password1" class="title">
                                    Password
                                </label>
                                {{form.password1.errors}}
                                <div class="input-field">
                                    {{form.password1}}
                                </div>
                            </div>
                            <div class="confirm-password-field pull-right">
                                <label for="id_password2" class="title">
                                    Confirm Password
                                </label>
                                {{form.password2.errors}}
                                <div class="input-field">
                                    {{form.password2}}
                                </div>
                            </div>
                        </div>
                        
                        <div class="email-gender-section data-row row-fluid">
                            <div class="email-field pull-left">
                                <label for="id_email" class="title">
                                    Email
                                </label>
                                {{form.email.errors}}
                                <div class="input-field">
                                    {{form.email}}
                                </div>
                            </div>
                            <div class="gender-section pull-left">
                                <label for="id_gender" class="title">
                                    Gender
                                </label>
                                {{form.gender.errors}}
                                <div class="input-field">
                                    {{form.gender}}
                                </div>
                            </div>
                        </div>
                        
                        <div class="complete-section row-fluid">
                            <div class='left-content pull-left'>
                                <div class="register-btn pull-right">
                                    <input id="register_btn" type="image" src="{{STATIC_URL}}img/app/account/register-btn.png" alt="Register">
                                </div>
                            </div>
                            <div class="right-content pull-right">
                                Already a member? <a href="/login"> Sign In </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

{% endblock %}

stomory/asset/templates/app/account/page/social_signup.html
{% extends "app/account/account_base.html" %}

{% block main_section %}
            <div class="social-signup-section">
                <div class="social-signup-header row-fluid">
                    <div class="header-text pull-left">
                        Signup with Facebook
                    </div>
                </div>
                <div class="social-signup-content row-fluid">
                    <form class="signup" id="social_signup_form" method="post" action="">{% csrf_token %}
                        <div class='non-field-error row-fluid'>
                            {{ form.non_field_errors }}
                        </div>

                        <div class="email-section data-row row-fluid">
                            <div class="email-field pull-left">
                                <label for="id_email" class="title">
                                    Email
                                </label>
                                {{form.email.errors}}
                                <div class="input-field">
                                    {{form.email}}
                                </div>
                            </div>
                        </div>
                        
                        <div class="complete-section row-fluid">
                            <div class="submit-btn">
                                <input id="social-signup_btn" type="image" src="{{STATIC_URL}}img/app/account/register-btn.png" alt="social-signup">
                            </div>
                        </div>
                    </form>
                </div>
            </div>

{% endblock %}